# site settings
title: HuAo
subtitle: huao-blog
<<<<<<< HEAD
email: 3047401843@qq.com
=======
email: 3047401843@qq.com 
>>>>>>> 8dd4bff784fe858f1c32c119aa60aae3bd5661ad
description: 站在巨人的肩上改变世界
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
<<<<<<< HEAD
#street_address: 1234 Somewhere Road
city: WuHan
#state: TN
#zip_code: 55555
=======
# street_address: 1234 Somewhere Road
city: WuHan
# state: TN
# zip_code: 55555
>>>>>>> 8dd4bff784fe858f1c32c119aa60aae3bd5661ad
country: China
phone: 15926219478

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
